apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: mern-app
type: Opaque
stringData:
  mongo-root-username: admin
  mongo-root-password: admin123
  mongo-connection-string: mongodb://admin:admin123@mongodb-service:27017/tododb?authSource=admin
